/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as OrganizerOrganizerIdEventsImport } from './routes/organizer/$organizerId/events'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OrganizerOrganizerIdEventsRoute = OrganizerOrganizerIdEventsImport.update(
  {
    id: '/organizer/$organizerId/events',
    path: '/organizer/$organizerId/events',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/organizer/$organizerId/events': {
      id: '/organizer/$organizerId/events'
      path: '/organizer/$organizerId/events'
      fullPath: '/organizer/$organizerId/events'
      preLoaderRoute: typeof OrganizerOrganizerIdEventsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizer/$organizerId/events': typeof OrganizerOrganizerIdEventsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizer/$organizerId/events': typeof OrganizerOrganizerIdEventsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/organizer/$organizerId/events': typeof OrganizerOrganizerIdEventsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/organizer/$organizerId/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/organizer/$organizerId/events'
  id: '__root__' | '/' | '/organizer/$organizerId/events'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizerOrganizerIdEventsRoute: typeof OrganizerOrganizerIdEventsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizerOrganizerIdEventsRoute: OrganizerOrganizerIdEventsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/organizer/$organizerId/events"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/organizer/$organizerId/events": {
      "filePath": "organizer/$organizerId/events.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
